_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 55
                - 77
            "2":
                - 1
                - 55
                - 77
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.10.15
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 8
device_id:
    value: 2
evaluate_on_test:
    value: false
hidden_channels:
    value: 32
lr:
    value: 0.01
name:
    value: TNF-A
num_blocks:
    value: 4
num_epochs:
    value: 30
num_layers:
    value: 2
num_workers:
    value: 1
task:
    value: regression
train_ratio:
    value: 0.6
use_wandb:
    value: true
valid_ratio:
    value: 0.2
wandb_entity:
    value: team_ryoji
wandb_name:
    value: TNF-A_model
wandb_project:
    value: insilico
